server:
  port: 8082
spring:
  application:
    name: inventory-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://inventory-db:5432/inventory}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://discovery-service:8761/eureka}